# Generated by Django 5.1.3 on 2024-11-26 09:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://th.bing.com/th/id/R.ac9a5b6feab8bed63cd5423a02d6d187?rik=rxIxeWM1jpfEVQ&pid=ImgRaw&r=0",
                max_length=255,
                verbose_name="profile_pictures/",
            ),
        ),
    ]
