# Generated by Django 5.1.3 on 2024-11-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tractors", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tractor",
            name="seller",
            field=models.ForeignKey(
                limit_choices_to={"role": "seller"},
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customuser",
            ),
        ),
    ]
