# Generated by Django 5.1.3 on 2024-11-26 09:05

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tractors", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tractor",
            name="hours_used",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="tractor",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="images"
            ),
        ),
        migrations.AlterField(
            model_name="tractor",
            name="seller",
            field=models.ForeignKey(
                limit_choices_to={"role": "seller"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tractors",
                to="users.customuser",
            ),
        ),
    ]
