# Generated by Django 5.1.3 on 2024-11-26 09:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tractors", "0003_alter_tractor_hours_used_alter_tractor_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tractor",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="https://th.bing.com/th/id/R.dad5ba00175c745c791daf38577a4641?rik=o8VwnymG%2b2xzlg&pid=ImgRaw&r=0",
                max_length=255,
                verbose_name="images",
            ),
        ),
    ]
