// Import the Product interface
import { Product } from "./types/Product";

// Mock data for products
export const mockProducts: Product[] = [
  // 8 new products
  {
    id: "1",
    brandName: "John Deere",
    type: "Tractor",
    power: "100 HP",
    reviews: 4.5,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 950000,
    age: "2 yrs",
    miles: "0 miles",
    location: "Nairobi",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },
  {
    id: "2",
    brandName: "Kubota",
    type: "Tractor",
    power: "120 HP",
    reviews: 4.2,
    image: "img/tractor-images/tr-2.png",
    price: 890000,
    age: "1 yr",
    miles: "500 miles",
    location: "Mombasa",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "3",
    brandName: "Kubota",
    type: "Tractor",
    power: "120 HP",
    reviews: 4.2,
    image: "img/tractor-images/tr-1.png",
    price: 890000,
    age: "1 yr",
    miles: "500 miles",
    location: "Mombasa",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "4",
    brandName: "Kubota",
    type: "Tractor",
    power: "120 HP",
    reviews: 4.2,
    image: "/img/tractor-images/JD_6XXXB_OOS.png",
    price: 890000,
    age: "1 yr",
    miles: "500 miles",
    location: "Mombasa",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "5",
    brandName: "John Deere",
    type: "Tractor",
    power: "100 HP",
    reviews: 4.5,
    image: "img/tractor-images/tr-2.png",
    price: 950000,
    age: "2 yrs",
    miles: "0 miles",
    location: "Nairobi",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },
  {
    id: "6",
    brandName: "John Deere",
    type: "Tractor",
    power: "100 HP",
    reviews: 4.5,
    image: "img/tractor-images/tr-1.png",
    price: 950000,
    age: "2 yrs",
    miles: "0 miles",
    location: "Nairobi",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },
  {
    id: "7",
    brandName: "John Deere",
    type: "Tractor",
    power: "100 HP",
    reviews: 4.5,
    image: "img/tractor-images/tr-2.png",
    price: 950000,
    age: "2 yrs",
    miles: "0 miles",
    location: "Nairobi",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },
  {
    id: "8",
    brandName: "John Deere",
    type: "Tractor",
    power: "100 HP",
    reviews: 4.5,
    image: "img/tractor-images/tr-1.png",
    price: 950000,
    age: "2 yrs",
    miles: "0 miles",
    location: "Nairobi",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },

  // 8 used products
  {
    id: "9",
    brandName: "Massey Ferguson",
    type: "Tractor",
    power: "90 HP",
    reviews: 4.8,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 720000,
    age: "5 yrs",
    miles: "4000 miles",
    location: "Eldoret",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "10",
    brandName: "Massey Ferguson",
    type: "Tractor",
    power: "90 HP",
    reviews: 4.8,
    image: "img/tractor-images/tr-1.png",
    price: 720000,
    age: "5 yrs",
    miles: "4000 miles",
    location: "Eldoret",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "11",
    brandName: "Massey Ferguson",
    type: "Tractor",
    power: "90 HP",
    reviews: 4.8,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 720000,
    age: "5 yrs",
    miles: "4000 miles",
    location: "Eldoret",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "12",
    brandName: "Massey Ferguson",
    type: "Tractor",
    power: "90 HP",
    reviews: 4.8,
    image: "img/tractor-images/tr-1.png",
    price: 720000,
    age: "5 yrs",
    miles: "4000 miles",
    location: "Eldoret",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "13",
    brandName: "Massey Ferguson",
    type: "Tractor",
    power: "90 HP",
    reviews: 4.8,
    image: "img/tractor-images/tr-2.png",
    price: 720000,
    age: "5 yrs",
    miles: "4000 miles",
    location: "Eldoret",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "14",
    brandName: "Massey Ferguson",
    type: "Tractor",
    power: "90 HP",
    reviews: 4.8,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 720000,
    age: "5 yrs",
    miles: "4000 miles",
    location: "Eldoret",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },

  // 8 fast-moving products
  {
    id: "17",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/tr-1.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "18",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/tr-2.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "19",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "20",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/tr-1.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "21",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/tr-2.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "22",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "23",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/tr-1.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "24",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/tr-2.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },
  {
    id: "25",
    brandName: "Case IH",
    type: "Tractor",
    power: "110 HP",
    reviews: 4.9,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 1200000,
    age: "3 yrs",
    miles: "2500 miles",
    location: "Nakuru",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: true,
  },


  // 8 near-me products
  {
    id: "25",
    brandName: "New Holland",
    type: "Tractor",
    power: "80 HP",
    reviews: 4.7,
    image: "img/tractor-images/tr-1.png",
    price: 850000,
    age: "4 yrs",
    miles: "3500 miles",
    location: "Kisumu", 
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: true,
  },
  {
    id: "26",
    brandName: "New Holland",
    type: "Tractor",
    power: "80 HP",
    reviews: 4.7,
    image: "img/tractor-images/tr-2.png",
    price: 850000,
    age: "4 yrs",
    miles: "3500 miles",
    location: "Kisumu", 
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "used",
    fastMoving: true,
  },
  {
    id: "27",
    brandName: "New Holland",
    type: "Tractor",
    power: "80 HP",
    reviews: 4.7,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 850000,
    age: "4 yrs",
    miles: "3500 miles",
    location: "Kisumu", 
    logo: 'img/Logo/johndeere.png/',
    wd: '4WD',
    condition: "used",
    fastMoving: true,
  },
  {
    id: "28",
    brandName: "New Holland",
    type: "Tractor",
    power: "80 HP",
    reviews: 4.7,
    image: "img/tractor-images/tr-1.png",
    price: 850000,
    age: "4 yrs",
    miles: "3500 miles",
    location: "Kisumu", 
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: true,
  },
  {
    id: "29",
    brandName: "New Holland",
    type: "Tractor",
    power: "80 HP",
    reviews: 4.7,
    image: "img/tractor-images/tr-2.png",
    price: 850000,
    age: "4 yrs",
    miles: "3500 miles",
    location: "Kisumu", 
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "used",
    fastMoving: true,
  },
  {
    id: "30",
    brandName: "New Holland",
    type: "Tractor",
    power: "80 HP",
    reviews: 4.7,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 850000,
    age: "4 yrs",
    miles: "3500 miles",
    location: "Kisumu", 
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: true,
  },
  {
    id: "31",
    brandName: "New Holland",
    type: "Tractor",
    power: "80 HP",
    reviews: 4.7,
    image: "img/tractor-images/tr-1.png",
    price: 850000,
    age: "4 yrs",
    miles: "3500 miles",
    location: "Kisumu", 
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "used",
    fastMoving: true,
  },
  {
    id: "232",
    brandName: "New Holland",
    type: "Tractor",
    power: "80 HP",
    reviews: 4.7,
    image: "img/tractor-images/tr-2.png",
    price: 850000,
    age: "4 yrs",
    miles: "3500 miles",
    location: "Kisumu", 
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: true,
  },
 

  // 8 under 1M Ksh products
  {
    id: "33",
    brandName: "Mahindra",
    type: "Tractor",
    power: "75 HP",
    reviews: 4.4,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 700000,
    age: "6 yrs",
    miles: "5000 miles",
    location: "Garissa",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "34",
    brandName: "Mahindra",
    type: "Tractor",
    power: "75 HP",
    reviews: 4.4,
    image: "img/tractor-images/tr-1.png",
    price: 700000,
    age: "6 yrs",
    miles: "5000 miles",
    location: "Garissa",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "35",
    brandName: "Mahindra",
    type: "Tractor",
    power: "75 HP",
    reviews: 4.4,
    image: "img/tractor-images/tr-2.png",
    price: 700000,
    age: "6 yrs",
    miles: "5000 miles",
    location: "Garissa",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "36",
    brandName: "Mahindra",
    type: "Tractor",
    power: "75 HP",
    reviews: 4.4,
    image: "img/tractor-images/JD_6XXXB_OOS.pngg",
    price: 700000,
    age: "6 yrs",
    miles: "5000 miles",
    location: "Garissa",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "used",
    fastMoving: false,
  },
  {
    id: "37",
    brandName: "Mahindra",
    type: "Tractor",
    power: "75 HP",
    reviews: 4.4,
    image: "img/tractor-images/tr-1.png",
    price: 700000,
    age: "6 yrs",
    miles: "0 miles",
    location: "Garissa",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },
  {
    id: "38",
    brandName: "Mahindra",
    type: "Tractor",
    power: "75 HP",
    reviews: 4.4,
    image: "img/tractor-images/tr-2.png",
    price: 700000,
    age: "6 yrs",
    miles: "0 miles",
    location: "Garissa",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },
  {
    id: "39",
    brandName: "Mahindra",
    type: "Tractor",
    power: "75 HP",
    reviews: 4.4,
    image: "img/tractor-images/JD_6XXXB_OOS.png",
    price: 700000,
    age: "6 yrs",
    miles: "0 miles",
    location: "Garissa",
    logo: 'img/Logo/mahindra.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },
  {
    id: "40",
    brandName: "Mahindra",
    type: "Tractor",
    power: "75 HP",
    reviews: 4.4,
    image: "img/tractor-images/tr-1.png",
    price: 700000,
    age: "6 yrs",
    miles: "0 miles",
    location: "Garissa",
    logo: 'img/Logo/johndeere.png',
    wd: '4WD',
    condition: "new",
    fastMoving: false,
  },
  
  
];
